apiVersion: v1
kind: Pod

metadata:
  name: pvc-test-pod

spec:
  containers:
  - name: nginx
    image: nginx:latest

    volumeMounts:
    - name: my-storage
      mountPath: /data

  volumes:
  - name: my-storage
    persistentVolumeClaim:
      claimName: my-pvc
